---
title: "Exam 2 practice"
author: "Dr. Melissa Wuellner & Dr. Jacob C. Cooper"
format: html
editor: visual
---

## Exam 2 Practice

The following is practice for the exam. Please work through these problems and be ready to discuss them in class.

## Question 1: Cyclones

Consider this short data set:

| Latitude band | Season | Number of cyclones |
|---------------|--------|--------------------|
| 40 - 49° S    | Fall   | 370                |
| 40 - 49° S    | Winter | 452                |
| 40 - 49° S    | Spring | 273                |
| 40 - 49° S    | Summer | 422                |
| 50 - 59° S    | Fall   | 526                |
| 50 - 59° S    | Winter | 624                |
| 50 - 59° S    | Spring | 513                |
| 50 - 59° S    | Summer | 1,059              |
| 60 - 69° S    | Fall   | 980                |
| 60 - 69° S    | Winter | 1,200              |
| 60 - 69° S    | Spring | 995                |
| 60 - 69° S    | Summer | 1,751              |

All of the data was collected in the same year to determine whether the occurrences of cyclones differed by latitude and season around Antarctica. Use this data to answer the following questions.

a)  Classify each of the three variables above as either an explanatory or a response variable. Justify your answer.
b)  Classify each of the three variables above as either a nominal, ordinal, interval, or ratio variable. Justify your answer.
c)  State the null and alternative hypotheses for this scenario. Note: there are two sets of null/alternative hypotheses.
d)  Calculate the mean, median, and mode of your response variable. Based on your results, would you expect your data to be normally distributed or not? Justify your answer.
e)  Let’s say now that you’re testing the null hypothesis that the mean number of cyclones in this one year is similar to the average year. The mean number of cyclones per year across all years of data collected is 650 with a standard deviation of 425. Calculate the z-score and make a decision regarding the null hypothesis.

## Question 2: Minnows

Consider this scenario: You have discovered a never-before-documented population of minnow in the Kearney Canal near campus. During your first sampling trip, you notice that the total length (i.e., measured from the tip of the snout to the very tip of the tail) of the fish you measure appear to be smaller than the average total length of the species as recorded among all known individuals across their range. The mean total length noted in one publication is 85 mm with a standard deviation of 4.50. Below is your data the data from 20 minnows that you captured during your first sampling trip to the Kearney Canal:

| Fish ID | Length (mm) |
|---------|-------------|
| 1       | 89          |
| 2       | 75          |
| 3       | 86          |
| 4       | 74          |
| 5       | 69          |
| 6       | 100         |
| 7       | 73          |
| 8       | 69          |
| 9       | 96          |
| 10      | 79          |
| 11      | 61          |
| 12      | 62          |
| 13      | 95          |
| 14      | 98          |
| 15      | 100         |
| 16      | 57          |
| 17      | 70          |
| 18      | 78          |
| 19      | 65          |
| 20      | 65          |

a)  State the null and alternative hypothesis for your study.
b)  Calculate the median, first and third quartiles, and interquartile range of your response variable. Create a boxplot. Based on your results, are there any outliers in your data? Explain.
c)  Calculate the $z$-score for this scenario. Please show all of your work.
d)  What is the probability that, by random chance alone, you would find your observed mean or something more extreme?
e)  Assume that you set your $\alpha$ for your study prior to your data collection to $0.05$. Based on this information and the $p$-value you obtained for part $c$ above, is your null hypothesis supported or rejected?
