# Introduction {.unnumbered}

**Welcome to Biology 305 at the University of Nebraska at Kearney!**

In this class, you will learn:

1.  The basics of study design, the importance of understanding your research situation before embarking on a full study, and practice creating research frameworks based on different scenarios.
2.  The basics of data analysis, including understanding what kind of variables are being collected, why understanding variable types are important, and basic tests to understand univariate distributions.
3.  Basic multivariate statistics, including ANOVA, correlation, and regression, for comparing multiple different groups.
4.  The basics of coding and working in *R* for performing statistical analyses.

This site will help you navigate different homework assignments to perform the necessary *R* tests.

***Welcome to class!***

# Class authors

-   [Dr. Melissa Wuellner](https://scholar.google.com/citations?user=yQDewvEAAAAJ)

Primary lecture designer, author of many of the example problems.

-   [Dr. Jacob C. Cooper](https://scholar.google.com/citations?user=Q82K8tsAAAAJ)

Primary website designer, primary *R* coding for site

-   [Caleb Rother](https://calebrother.github.io/)

Teaching assistant, website designer, works with homework and coding
