---
title: "Two sample key"
author: "UNK Stats"
date: "`r Sys.Date()`"
output: pdf_document
---

# Question 1

```{r, echo = F, results = F}
owner_name <- c(2.0,1.3,3.4,2.6,2.6,0.8,2.6,1.9,0.3,0.9)
owner_sight <- c(2.8,4.3,3.0,3.9,2.7,3.4,3.3,3.7,2.8,3.4)

dog_data <- cbind(owner_name, owner_sight) |> 
  as.data.frame()
```

```{r, echo = F, results = F}
t.test(owner_name, owner_sight, paired = T, alternative = "less")
```

The test is significant ($t = -4.03$, $p = 0.001$).

# Question 2

```{r, echo = F, results = F}
rufula <- c(68.6,71.7,69.9,74.9,70.2,64.9,70.8,74.2,67.1,70.8,75.0,70.7)
melanocrissus <- c(73.8,82.1,70.5,75.4,73.4,67.4,71.5,75.9,68.6,72.4,67.5,73.8)

swallows <- cbind(rufula, melanocrissus) |> 
  as.data.frame()

t.test(rufula, melanocrissus)
```

The test is not significant ($t = -1.32$, $p = 0.20$).

# Question 3

```{r, echo = F, results = F}
habanero <- c(105.5,100.7,96.5,107.3,100.6,96.3,99.5,
              98.9,107.4,103.8,109.3,107.7,103.2,104.5,
              95.4,103.3,107.5,101.8,106.1,102.6)
jalapeño <- c(109.1,111.7,118.6,111.1,100.5,118.7,117.5,
              102.1,94.9,104.0,109.2,101.1,113.0,111.3,97.6,
              109.2,93.4,103.4,90.3,109.2)
  
peppers <- cbind(jalapeño, habanero) |> as.data.frame()

t.test(jalapeño, habanero, alternative = "greater")
```

The test is not significant ($t = 1.64$, $p = 0.06$).

# Question 4

```{r, echo = F, results = F}
versicolor <- iris |> 
  dplyr::filter(Species == "versicolor")
virginica <- iris |> 
  dplyr::filter(Species == "virginica")

# DATA CANNOT BE NORMALIZED

wilcox.test(versicolor$Petal.Width, virginica$Petal.Width)
```

The test is significant ($p < 0.0001$).

# Question 5: Bacteria counts

```{r, echo = F, results = F, warning = F}
media_A <- c(16,14,12,16,16,16,13,16,15,15,
             15,15,15,15,17,15,16,15,15,13,
             15,15,15,14,14,14,15,15,15,15,
             14,14,14,16,17,15,13,14,16,16)

media_B <- c(12,12,12,12,11,11,11,13,12,11,
             11,11,10,11,13,10,10,11,17,15,
             13,14,18,16,19,15,16,16,15,19,
             16,17,16,20,16,15,19,16,18,18)

# data cannot be normalized!

wilcox.test(media_A, media_B, alternative = "greater")
```

The test is not significant ($p = 0.15$).

# Question 6: Flint, Michigan

```{r, echo = F, results = F, message = F}
library(tidytuesdayR)

tuesdata <- tidytuesdayR::tt_load('2025-11-04')

flint_mdeq <- tuesdata$flint_mdeq |> 
  dplyr::select(-notes) |> 
  na.omit() |> 
  dplyr::select(-lead2)

group1 <- flint_mdeq[1:20,]
group2 <- flint_mdeq[21:40,]

# need to log1p transform

t.test(log1p(group1$lead), log1p(group2$lead))
```

The groups are significantly different ($p = 0.007$).

```{r, echo = F, results = F}
sum(flint_mdeq$lead>15)/nrow(flint_mdeq)
```

No, there is only 8.7% (0.09) of households with bad lead in this sample.